### ISSUE TITLE
Error in installing model

### ISSUE THREAD

**Issue by Soebb** [zackees/pydeepspeech#3]
File "/usr/lib/python3.9/ssl.py", line 1040, in _create

self.do_handshake() self.do_handshake()

File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake

File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake

self._sslobj.do_handshake()self._sslobj.do_handshake()

sslssl..SSLCertVerificationErrorSSLCertVerificationError: : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 793, in urlopen

Traceback (most recent call last):

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 793, in urlopen

response = self._make_request(response = self._make_request(

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 491, in _make_request

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 491, in _make_request

raise new_eraise new_e

urllib3.exceptions.

SSLErrorurllib3.exceptions.SSLError: : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

The above exception was the direct cause of the following exception:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

Traceback (most recent call last):

File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send

File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send

resp = conn.urlopen(

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 847, in urlopen

resp = conn.urlopen(

File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 847, in urlopen

retries = retries.increment(

File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment

raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='itml.cl.indiana.edu', port=443): Max retries exceeded with url: /models/fa/kenlm.scorer (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

retries = retries.increment(

File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment

self.run()

File "/usr/lib/python3.9/threading.py", line 892, in run

raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]self._target(*self._args, **self._kwargs)

urllib3.exceptions. File "/usr/local/lib/python3.9/dist-packages/pydeepspeech/installModels.py", line 29, in download_file

MaxRetryError: HTTPSConnectionPool(host='itml.cl.indiana.edu', port=443): Max retries exceeded with url: /models/fa/output_graph.pbmm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

with requests.get(url, stream=True) as r:

File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get

self.run()

File "/usr/lib/python3.9/threading.py", line 892, in run

return request("get", url, params=params, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request

self._target(*self._args, **self._kwargs)

File "/usr/local/lib/python3.9/dist-packages/pydeepspeech/installModels.py", line 29, in download_file

return session.request(method=method, url=url, **kwargs)

with requests.get(url, stream=True) as r:

File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request

File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get

return request("get", url, params=params, **kwargs)

resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request

File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send

return session.request(method=method, url=url, **kwargs)

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 517, in send

File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request

raise SSLError(e, request=request) resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send

requests.exceptions.SSLError: HTTPSConnectionPool(host='itml.cl.indiana.edu', port=443): Max retries exceeded with url: /models/fa/kenlm.scorer (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 517, in send

raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='itml.cl.indiana.edu', port=443): Max retries exceeded with url: /models/fa/output_graph.pbmm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

Traceback (most recent call last):

File "/usr/local/bin/pydeepspeech", line 8, in <module>

sys.exit(main())

File "/usr/local/lib/python3.9/dist-packages/pydeepspeech/run.py", line 31, in main

check_path(os.path.join(model_dir,'deepspeech-0.9.3-models.scorer'))

File "/usr/local/lib/python3.9/dist-packages/pydeepspeech/run.py", line 14, in check_path

raise OSError(f'Did not find expected path {path}')

OSError: Did not find expected path /root/.cache/pip/pydeepspeech_models/model/v0.9.3/deepspeech-0.9.3-models.scorer

**Comment by zackees** [comment]
Py deep speech is no longer supported. Use transcribe-anything instead.

**Comment by Soebb** [comment]
Fixed with

> import requests
> requests.packages.urllib3.disable_warnings()

&

> requests.get(url, stream=True, verify=False)

In install_models.py

**Comment by zackees** [comment]
Thank you for this. But why are you using pydeep speech? It seems inferior to whisper ai. My `transcribe-anything` tool is the best whisper front end on the planet.

**Comment by Soebb** [comment]
I knew and always use it, thanks for that.
i just was curious about deepspeech to try.
